runtest: colorful output

diff --git a/build/runtest b/build/runtest
--- a/build/runtest
+++ b/build/runtest
@@ -20,43 +20,49 @@ msg="${txt%.txt}.msg"
 chk="${src%.spl}.chk"
 gold="${src%.spl}.log"
 
-#echo "RUNTEST: $src: compiling..."
+RED='\033[0;7;31m'
+GRN='\033[0;32m'
+OFF='\033[0m'
+PASS=${GRN}PASS${OFF}
+FAIL=${RED}FAIL${OFF}
+
+#echo "TEST: $src: compiling..."
 if compile "$src" "$bin" 2> "$msg"; then
 	# success!
 	if [[ "$txt" == *"-err"* ]]; then
 		# but this was an error test, so...
-		echo "RUNTEST: $src: FAIL: compiler did not detect error"
+		echo -e "${FAIL}: $src: compiler did not detect error"
 		echo "FAIL: $src" > "$txt"
 	else
-		#echo "RUNTEST: $src: running..."
+		#echo "TEST: $src: running..."
 		if run "$bin" "$chk" > "$log"; then
 			if diff "$log" "$gold" >/dev/null ; then
-				echo "RUNTEST: $src: PASS"
+				echo -e "${PASS}: $src"
 				echo "PASS: $src" > "$txt"
 			else
-				echo "RUNTEST: $src: FAIL: output differs from expected"
+				echo -e "${FAIL}: $src: output differs from expected"
 				diff "$log" "$gold" | head
 				echo "FAIL: $src" > "$txt"
 			fi
 		else
-			echo "RUNTEST: $src: FAIL: emulator crashed"
+			echo -e "${FAIL}: $src: emulator crashed"
 			echo "FAIL: $src" > "$txt"
 		fi
 	fi
 else
-	if [[ $? > 127 ]]; then
-		echo "RUNTEST: $src: FAIL: compiler crashed"
-		echo "FAIL: $src" > "$txt"
-		cat "$msg"
 	# failure
+	if [[ $? > 127 ]]; then
+		echo -e "${FAIL}: $src: compiler crashed"
+		echo "FAIL: $src" > "$txt"
+		cat "$msg" | grep -v '^$'
 	elif [[ "$txt" == *"-err"* ]]; then
 		# but this was an error test, so...
-		echo "RUNTEST: $src: PASS"
+		echo -e "${PASS}: $src"
 		echo "PASS: $src" > "$txt"
 	else
-		echo "RUNTEST: $src: FAIL: compiler error"
+		echo -e "${FAIL}: $src: compiler error"
 		echo "FAIL: $src" > "$txt"
-		cat "$msg"
+		cat "$msg" | grep -v '^$'
 	fi
 fi
 
